<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Form1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Form1Repository extends EntityRepository
{
}
