AppBundle\Entity\Form1:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\Form1Repository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userid:
            type: integer
            unique: true
        p1:
            type: string
            length: 2
        p1porque:
            type: text
        p2:
            type: string
            length: 2
        p2porque:
            type: text
        p3:
            type: string
            length: 2
        p3porque:
            type: text          
    lifecycleCallbacks: {  }
